"""empty message

Revision ID: 95f1e890c9dd
Revises: b8dd3c0a6591
Create Date: 2026-04-19 13:49:06.621148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95f1e890c9dd'
down_revision = 'b8dd3c0a6591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cproblem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ans_field', sa.String(length=1024), nullable=True))
        batch_op.drop_column('choices')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cproblem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('choices', mysql.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('ans_field')

    # ### end Alembic commands ###
