"""empty message

Revision ID: b8dd3c0a6591
Revises: 
Create Date: 2026-04-19 13:19:15.036903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8dd3c0a6591'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cproblem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('choices', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cproblem', schema=None) as batch_op:
        batch_op.drop_column('choices')

    # ### end Alembic commands ###
